import AppHeader from "@/components/AppHeader";
import ErrorFallback from "@/components/ErrorFallback";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "@/providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ErrorBoundary } from "react-error-boundary";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ak's Todo List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppHeader />
          <ErrorBoundary FallbackComponent={ErrorFallback}>
            {children}
          </ErrorBoundary>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
